"use strict";
exports.__esModule = true;
var product_1 = require("./product");
var productManager_1 = require("./productManager");
var laptop = new product_1.Product('Laptop', 20000);
var iphone = new product_1.Product('iPhone', 15000);
var productManager = new productManager_1.ProductManager();
productManager.add = laptop;
productManager.add = iphone;
console.log(productManager.getAll);
